# Generated by Django 2.0.1 on 2018-01-15 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futureFleet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
